backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
  - label: "Blurbs"
    name: "blurb"
    folder: "site/content/blurbs"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - {label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Events"
    name: "event"
    folder: "site/content/events"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - {label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "howTos"
    name: "How to"
    folder: "site/content/howTos"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Petitions"
    name: "petition"
    folder: "site/content/petitions"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Petition Link", name: "link", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Videos"
    name: "video"
    folder: "site/content/videos"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video Link", name: "link", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }