name: Sync Markdown Files

on:
  push:
    branches:
      - main
    paths:
      - 'site/content/blurbs/**/*.md'
      - 'site/content/events/**/*.md'
      - 'site/content/howTos/**/*.md'
      - 'site/content/petitions/**/*.md'
      - 'site/content/videos/**/*.md'
  delete:
    paths:
      - 'site/content/blurbs/**/*.md'
      - 'site/content/events/**/*.md'
      - 'site/content/howTos/**/*.md'
      - 'site/content/petitions/**/*.md'
      - 'site/content/videos/**/*.md'
  workflow_dispatch:

jobs:
  sync-markdown:
    runs-on: ubuntu-latest

    steps:
      # Check out the source repository
      - name: Checkout source repo
        uses: actions/checkout@v3

      # Copy folders to a temporary directory
      - name: Copy folders
        run: |
          mkdir -p ./temp_content
          cp -r ./site/content/blurbs ./site/content/events ./site/content/howTos ./site/content/petitions ./site/content/videos ./temp_content/

      # Check out the target repository
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: Submerge2681/11ty-template
          token: ${{ secrets.CMS_TOKEN }}
          path: target-repo

      # Copy folders to the target repository
      - name: Copy folders to target repo
        run: |
          mkdir -p ./target-repo/src  # Ensure /src directory exists
          cp -r ./temp_content/* ./target-repo/src/

      # Commit and push
      - name: Commit and push changes
        run: |
          cd target-repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Sync Markdown Files"
          git push
